In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
!unrar x gdrive/My\ Drive/Reduced/train.rar gdrive/My\ Drive/Reduced/data


UNRAR 5.50 freeware      Copyright (c) 1993-2017 Alexander Roshal


Extracting from gdrive/My Drive/Reduced/train.rar

Creating    gdrive/My Drive/Reduced/data/train                        OK
Extracting  gdrive/My Drive/Reduced/data/train/100_left.jpeg               0%  OK 
Extracting  gdrive/My Drive/Reduced/data/train/100_right.jpeg              0%  OK 
Extracting  gdrive/My Drive/Reduced/data/train/102_left.jpeg               0%  OK 
Extracting  gdrive/My Drive/Reduced/data/train/102_right.jpeg              1%  OK 
Extracting  gdrive/My Drive/Reduced/data/train/104_left.jpeg               1%  OK 
Extracting  gdrive/My Drive/Reduced/data/train/104_right.jpeg              1%  OK 
Extracting  gdrive/My Drive/Reduced/data/train/108_left.jpeg               1%  OK 
Extracting  gdrive/My Drive/Reduced/data/train/108_right.jpeg              2%  OK 
Extracting  gdrive/My Drive/Reduced/data/train/10_left.jpeg            

Novo csv apenas com os dados do dataset reduzido

In [0]:
import pandas as pd
import os

files = [l.split('.')[0] for l in os.listdir("gdrive/My Drive/Reduced/data/train") if l != '.DS_Store']

labels = pd.read_csv("gdrive/My Drive/Capstone/labels/trainLabels.csv")
reduced_labels = labels[labels["image"].isin(files)]

reduced_labels.to_csv("gdrive/My Drive/Reduced/labels/trainLabels.csv")

reduced_labels.size

572

Redimensionando as imagens para 256 x 256

In [0]:
!ls gdrive/My\ Drive/Reduced

data  labels  train.rar


In [0]:
import sys
from PIL import ImageFile
from skimage import io
from skimage.transform import resize
import numpy as np

ImageFile.LOAD_TRUNCATED_IMAGES = True

def create_directory(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)


def crop_and_resize_images(path, new_path, cropx, cropy, img_size=256):
    
    create_directory(new_path)
    dirs = [l for l in os.listdir(path) if l != '.DS_Store']
    total = 0

    for item in dirs:
        img = io.imread(path+item)
        y,x,channel = img.shape
        startx = x//2-(cropx//2)
        starty = y//2-(cropy//2)
        img = img[starty:starty+cropy,startx:startx+cropx]
        img = resize(img, (256,256))
        io.imsave(str(new_path + item), img)
        total += 1
        print("Saving: ", item, total)

In [0]:
crop_and_resize_images(path="gdrive/My Drive/Reduced/data/train/", new_path="gdrive/My Drive/Reduced/data/train-resized-256/", cropx=1800, cropy=1800, img_size=256)

/usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
/usr/local/lib/python3.6/dist-packages/skimage/util/dtype.py:141: UserWarning: Possible precision loss when converting from float64 to uint8
  .format(dtypeobj_in, dtypeobj_out))


Saving:  100_left.jpeg 1
Saving:  100_right.jpeg 2
Saving:  102_left.jpeg 3
Saving:  102_right.jpeg 4
Saving:  104_left.jpeg 5
Saving:  104_right.jpeg 6
Saving:  108_left.jpeg 7
Saving:  108_right.jpeg 8
Saving:  10_left.jpeg 9
Saving:  10_right.jpeg 10
Saving:  111_left.jpeg 11
Saving:  111_right.jpeg 12
Saving:  114_left.jpeg 13
Saving:  114_right.jpeg 14
Saving:  115_left.jpeg 15
Saving:  115_right.jpeg 16
Saving:  117_left.jpeg 17
Saving:  117_right.jpeg 18
Saving:  119_left.jpeg 19
Saving:  119_right.jpeg 20
Saving:  122_left.jpeg 21
Saving:  122_right.jpeg 22
Saving:  125_left.jpeg 23
Saving:  125_right.jpeg 24
Saving:  129_left.jpeg 25
Saving:  129_right.jpeg 26
Saving:  13_left.jpeg 27
Saving:  13_right.jpeg 28
Saving:  140_left.jpeg 29
Saving:  140_right.jpeg 30
Saving:  145_left.jpeg 31
Saving:  145_right.jpeg 32
Saving:  149_left.jpeg 33
Saving:  149_right.jpeg 34
Saving:  155_left.jpeg 35
Saving:  155_right.jpeg 36
Saving:  156_left.jpeg 37
Saving:  156_right.jpeg 38
Saving

/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/204_left.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)
/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/204_right.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)
/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/208_left.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)


Saving:  208_left.jpeg 95
Saving:  208_right.jpeg 96


/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/208_right.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)


Saving:  20_left.jpeg 97
Saving:  20_right.jpeg 98
Saving:  210_left.jpeg 99
Saving:  210_right.jpeg 100
Saving:  211_left.jpeg 101
Saving:  211_right.jpeg 102
Saving:  214_left.jpeg 103
Saving:  214_right.jpeg 104
Saving:  216_left.jpeg 105
Saving:  216_right.jpeg 106
Saving:  217_left.jpeg 107
Saving:  217_right.jpeg 108
Saving:  218_left.jpeg 109
Saving:  218_right.jpeg 110
Saving:  219_left.jpeg 111
Saving:  219_right.jpeg 112
Saving:  21_left.jpeg 113
Saving:  21_right.jpeg 114
Saving:  222_left.jpeg 115
Saving:  222_right.jpeg 116
Saving:  224_left.jpeg 117
Saving:  224_right.jpeg 118
Saving:  225_left.jpeg 119
Saving:  225_right.jpeg 120
Saving:  227_left.jpeg 121
Saving:  227_right.jpeg 122
Saving:  229_left.jpeg 123
Saving:  229_right.jpeg 124
Saving:  22_left.jpeg 125
Saving:  22_right.jpeg 126
Saving:  231_left.jpeg 127
Saving:  231_right.jpeg 128
Saving:  232_left.jpeg 129
Saving:  232_right.jpeg 130
Saving:  234_left.jpeg 131
Saving:  234_right.jpeg 132
Saving:  236_left.j

/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/364_left.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)
/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/364_right.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)


Saving:  364_right.jpeg 250
Saving:  367_left.jpeg 251
Saving:  367_right.jpeg 252
Saving:  36_left.jpeg 253
Saving:  36_right.jpeg 254
Saving:  374_left.jpeg 255
Saving:  374_right.jpeg 256
Saving:  375_left.jpeg 257
Saving:  375_right.jpeg 258
Saving:  376_left.jpeg 259
Saving:  376_right.jpeg 260
Saving:  378_left.jpeg 261
Saving:  378_right.jpeg 262
Saving:  380_left.jpeg 263
Saving:  380_right.jpeg 264
Saving:  381_left.jpeg 265
Saving:  381_right.jpeg 266
Saving:  384_left.jpeg 267
Saving:  384_right.jpeg 268
Saving:  386_left.jpeg 269
Saving:  386_right.jpeg 270
Saving:  389_left.jpeg 271
Saving:  389_right.jpeg 272
Saving:  391_left.jpeg 273
Saving:  391_right.jpeg 274
Saving:  393_left.jpeg 275
Saving:  393_right.jpeg 276
Saving:  395_left.jpeg 277
Saving:  395_right.jpeg 278
Saving:  396_left.jpeg 279
Saving:  396_right.jpeg 280
Saving:  398_left.jpeg 281
Saving:  398_right.jpeg 282
Saving:  399_left.jpeg 283
Saving:  399_right.jpeg 284
Saving:  400_left.jpeg 285
Saving:  400

/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/72_left.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)
/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/72_right.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)


Saving:  73_left.jpeg 401
Saving:  73_right.jpeg 402
Saving:  74_left.jpeg 403
Saving:  74_right.jpeg 404
Saving:  75_left.jpeg 405
Saving:  75_right.jpeg 406
Saving:  78_left.jpeg 407
Saving:  78_right.jpeg 408
Saving:  79_left.jpeg 409
Saving:  79_right.jpeg 410
Saving:  81_left.jpeg 411
Saving:  81_right.jpeg 412
Saving:  82_left.jpeg 413
Saving:  82_right.jpeg 414
Saving:  84_left.jpeg 415
Saving:  84_right.jpeg 416
Saving:  95_left.jpeg 417
Saving:  95_right.jpeg 418
Saving:  99_left.jpeg 419
Saving:  99_right.jpeg 420


In [0]:
import os
dirs = [l for l in os.listdir("gdrive/My Drive/Reduced/data/train-resized-256") if l != '.DS_Store']
dirs2 = [l for l in os.listdir("gdrive/My Drive/Reduced/data/train") if l != '.DS_Store']

print(len(dirs))
print(len(dirs2))

1001
420


Removendo imagens com valores de contraste muito baixo



In [0]:
import time
from PIL import Image


def find_black_images(file_path, df):

    lst_imgs = [l for l in df['image']]
    return [1 if np.mean(np.array(Image.open(file_path + img))) == 0 else 0 for img in lst_imgs]

In [0]:
start_time = time.time()
trainLabels = pd.read_csv("gdrive/My Drive/Reduced/labels/trainLabels.csv")

trainLabels['image'] = [i + '.jpeg' for i in trainLabels['image']]
trainLabels['black'] = np.nan

trainLabels['black'] = find_black_images("gdrive/My Drive/Reduced/data/train-resized-256/", trainLabels)
trainLabels = trainLabels.loc[trainLabels['black'] == 0]
trainLabels.to_csv("gdrive/My Drive/Reduced/labels/trainLabels_master.csv", index=False, header=True)

print("Completed")
print("--- %s seconds ---" % (time.time() - start_time))

Completed
--- 0.7494277954101562 seconds ---


Aplica espelhamento  em imagens onde não é detectada doença. 
Rotaciona imagens em 90, 120, 180 e 270 graus, quando detectada a doença.

In [0]:
from skimage import io
from skimage.transform import rotate
import cv2

def rotate_images(file_path, degrees_of_rotation, lst_imgs):
    
    print("Size pkg for rotate: " + str(len(lst_imgs)))
    ia = 0
    for l in lst_imgs:
        ia += 1
        img = io.imread(file_path + str(l) + '.jpeg')
        img = rotate(img, degrees_of_rotation)
        io.imsave(file_path + str(l) + '_' + str(degrees_of_rotation) + '.jpeg', img)
        if(ia%100 == 0):
            print(ia)

def mirror_images(file_path, mirror_direction, lst_imgs):
    
    print("Size pkg for mirror: " + str(len(lst_imgs)))
    ia = 0
    for l in lst_imgs:
        ia += 1
        img = cv2.imread(file_path + str(l) + '.jpeg')
        img = cv2.flip(img, 1)
        cv2.imwrite(file_path + str(l) + '_mir' + '.jpeg', img)
        if(ia%100 == 0):
            print(ia)

In [0]:
start_time = time.time()
trainLabels = pd.read_csv("gdrive/My Drive/Reduced/labels/trainLabels_master.csv")

trainLabels['image'] = trainLabels['image'].str.rstrip('.jpeg')
trainLabels_no_DR = trainLabels[trainLabels['level'] == 0]
trainLabels_DR = trainLabels[trainLabels['level'] >= 1]

lst_imgs_no_DR = [i for i in trainLabels_no_DR['image']]
lst_imgs_DR = [i for i in trainLabels_DR['image']]

print("Mirroring Non-DR Images")
mirror_images("gdrive/My Drive/Reduced/data/train-resized-256/", 1, lst_imgs_no_DR)

print("Rotating 90 Degrees")
rotate_images("gdrive/My Drive/Reduced/data/train-resized-256/", 90, lst_imgs_DR)

print("Rotating 120 Degrees")
rotate_images("gdrive/My Drive/Reduced/data/train-resized-256/", 120, lst_imgs_DR)

print("Rotating 180 Degrees")
rotate_images("gdrive/My Drive/Reduced/data/train-resized-256/", 180, lst_imgs_DR)

print("Rotating 270 Degrees")
rotate_images('gdrive/My Drive/Reduced/data/train-resized-256/', 270, lst_imgs_DR)

print("Mirroring DR Images")
mirror_images("gdrive/My Drive/Reduced/data/train-resized-256/", 0, lst_imgs_DR)

print("Completed")
print("--- %s seconds ---" % (time.time() - start_time))

Mirroring Non-DR Images
Size pkg for mirror: 206
100
200
Rotating 90 Degrees
Size pkg for rotate: 75


/usr/local/lib/python3.6/dist-packages/skimage/util/dtype.py:141: UserWarning: Possible precision loss when converting from float64 to uint8
  .format(dtypeobj_in, dtypeobj_out))
/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/204_right_90.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)


Rotating 120 Degrees
Size pkg for rotate: 75


/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/204_right_120.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)


Rotating 180 Degrees
Size pkg for rotate: 75


/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/204_right_180.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)


Rotating 270 Degrees
Size pkg for rotate: 75


/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:140: UserWarning: gdrive/My Drive/Reduced/data/train-resized-256/204_right_270.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)


Mirroring DR Images
Size pkg for mirror: 75
Completed
--- 9.6828134059906 seconds ---


Gerando o csv com para o novo conjunto de imagens, e removendo as labels das imagens com baixo contraste

In [0]:
def get_lst_images(file_path):
    
    return [i for i in os.listdir(file_path) if i != '.DS_Store']


trainLabels = pd.read_csv("gdrive/My Drive/Reduced/labels/trainLabels_master.csv")

lst_imgs = get_lst_images("gdrive/My Drive/Reduced/data/train-resized-256/")

new_trainLabels = pd.DataFrame({'image': lst_imgs})
new_trainLabels['image2'] = new_trainLabels.image


new_trainLabels['image2'] = new_trainLabels.loc[:, 'image2'].apply(lambda x: '_'.join(x.split('_')[0:2]))


new_trainLabels['image2'] = new_trainLabels.loc[:, 'image2'].apply(
    lambda x: '_'.join(x.split('_')[0:2]).strip('.jpeg') + '.jpeg')


new_trainLabels.columns = ['train_image_name', 'image']

trainLabels = pd.merge(trainLabels, new_trainLabels, how='outer', on='image')
trainLabels.drop(['black'], axis=1, inplace=True)

trainLabels = trainLabels.dropna()
print(trainLabels.shape)

print("Writing CSV")
trainLabels.to_csv("gdrive/My Drive/Reduced/labels/trainLabels_master_256_v2.csv", index=False, header=True)

(862, 4)
Writing CSV


Criando o array para o treinamento

In [0]:
def change_image_name(df, column):
  
    return [i + '.jpeg' for i in df[column]]


def convert_images_to_arrays_train(file_path, df):
  
    lst_imgs = [l for l in df['train_image_name']]

    return np.array([np.array(Image.open(file_path + img)) for img in lst_imgs])


def save_to_array(arr_name, arr_object):
  
    return np.save(arr_name, arr_object)

In [0]:
start_time = time.time()

labels = pd.read_csv("gdrive/My Drive/Reduced/labels/trainLabels_master_256_v2.csv")

print("Writing Train Array")
X_train = convert_images_to_arrays_train("gdrive/My Drive/Reduced/data/train-resized-256/", labels)

print(X_train.shape)

print("Saving Train Array")
save_to_array("gdrive/My Drive/Reduced/data/X_train.npy", X_train)

print("--- %s seconds ---" % (time.time() - start_time))

Writing Train Array
(862, 256, 256, 3)
Saving Train Array
--- 3.267965316772461 seconds ---


#trainning

## CNN Multi

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers.convolutional import Conv2D
from keras.utils import np_utils
from keras import backend as K
from keras.callbacks import EarlyStopping
from keras.callbacks import TensorBoard
import pandas as pd
import numpy as np
from keras.layers.normalization import BatchNormalization
from keras.optimizers import SGD
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.utils import class_weight
import os

np.random.seed(1337)


def split_data(X, y, test_data_size):
   
    return train_test_split(X, y, test_size=test_data_size, random_state=42)


def reshape_data(arr, img_rows, img_cols, channels):
   
    return arr.reshape(arr.shape[0], img_rows, img_cols, channels)


def cnn_model(X_train, X_test, y_train, y_test, kernel_size, nb_filters, channels, nb_epoch, batch_size, nb_classes):
   
    model = Sequential()


    model.add(Conv2D(nb_filters, (kernel_size[0], kernel_size[1]),
        padding='valid',
        strides=4,
        input_shape=(img_rows, img_cols, channels)))
    model.add(Activation('relu'))


    model.add(Conv2D(nb_filters, (kernel_size[0], kernel_size[1])))
    model.add(Activation('relu'))


    model.add(Conv2D(nb_filters, (kernel_size[0], kernel_size[1])))
    model.add(Activation('relu'))


    model.add(MaxPooling2D(pool_size=(2,2)))


    kernel_size = (16,16)
    model.add(Conv2D(64, (kernel_size[0], kernel_size[1])))
    model.add(Activation('relu'))
    # model.add(Dropout(0.2))


    model.add(MaxPooling2D(pool_size=(2,2)))


    model.add(Flatten())
    print("Model flattened out to: ", model.output_shape)


    model.add(Dense(128))
    model.add(Activation('sigmoid'))
    model.add(Dropout(0.25))

    model.add(Dense(nb_classes))
    model.add(Activation('softmax'))


    model.compile(loss = 'categorical_crossentropy',
                    optimizer='adam',
                    metrics=['accuracy'])


    stop = EarlyStopping(monitor='val_acc',
                            min_delta=0.001,
                            patience=2,
                            verbose=0,
                            mode='auto')


    tensor_board = TensorBoard(log_dir='./Graph', histogram_freq=0, write_graph=True, write_images=True)


    model.fit(X_train,y_train, batch_size=batch_size, epochs=nb_epoch,
                verbose=1,
                validation_split=0.2,
                class_weight=weights,
                callbacks=[stop, tensor_board])

    return model


def save_model(model, score, model_name):
    

    if score >= 0.75:
        print("Saving Model")
        model.save("gdrive/My Drive/Reduced/models/" + model_name + "_recall_" + str(round(score,4)) + ".h5")
    else:
        print("Model Not Saved.  Score: ", score)

Using TensorFlow backend.


In [0]:
os.environ["CUDA_VISIBLE_DEVICES"]="0,1,2,3"

# Specify parameters before model is run.
batch_size = 1000
nb_classes = 5
nb_epoch = 30

img_rows, img_cols = 256, 256
channels = 3
nb_filters = 32
kernel_size = (8,8)

# Import data
labels = pd.read_csv("gdrive/My Drive/Reduced/labels/trainLabels_master_256_v2.csv")
X = np.load("gdrive/My Drive/Reduced/data/X_train.npy")
y = np.array(labels['level'])


# Class Weights (for imbalanced classes)
print("Computing Class Weights")
weights = class_weight.compute_class_weight('balanced', np.unique(y), y)


print("Splitting data into test/ train datasets")
X_train, X_test, y_train, y_test = split_data(X, y, 0.2)


print("Reshaping Data")
X_train = reshape_data(X_train, img_rows, img_cols, channels)
X_test = reshape_data(X_test, img_rows, img_cols, channels)

print("X_train Shape: ", X_train.shape)
print("X_test Shape: ", X_test.shape)


input_shape = (img_rows, img_cols, channels)


print("Normalizing Data")
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

X_train /= 255
X_test /= 255


y_train = np_utils.to_categorical(y_train, nb_classes)
y_test = np_utils.to_categorical(y_test, nb_classes)
print("y_train Shape: ", y_train.shape)
print("y_test Shape: ", y_test.shape)


print("Training Model")


model = cnn_model(X_train, X_test, y_train, y_test, kernel_size, nb_filters, channels, nb_epoch, batch_size, nb_classes)


print("Predicting")
y_pred = model.predict(X_test)


score = model.evaluate(X_test, y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])


y_pred = [np.argmax(y) for y in y_pred]
y_test = [np.argmax(y) for y in y_test]


precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')


print("Precision: ", precision)
print("Recall: ", recall)


save_model(model=model, score=recall, model_name="DR_Two_Classes")


print("Completed")

Computing Class Weights
Splitting data into test/ train datasets
Reshaping Data
X_train Shape:  (689, 256, 256, 3)
X_test Shape:  (173, 256, 256, 3)
Normalizing Data
y_train Shape:  (689, 5)
y_test Shape:  (173, 5)
Training Model
Instructions for updating:
Colocations handled automatically by placer.
Model flattened out to:  (None, 1024)
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Train on 551 samples, validate on 138 samples
Epoch 1/30
551/551 [==============================] - 9s 16ms/step - loss: 1.8781 - acc: 0.1525 - val_loss: 1.3611 - val_acc: 0.5725
Epoch 2/30
551/551 [==============================] - 1s 1ms/step - loss: 1.5206 - acc: 0.4428 - val_loss: 1.5126 - val_acc: 0.1667
Epoch 3/30
551/551 [==============================] - 1s 950us/step - loss: 1.4789 - acc: 0.3358 - val_loss: 1.4282 - val_acc: 0.5217
Predicting
Test score: 1.4571428719283528
Test accur

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
